Secondary branch
pountzas/Project-1-Positioning-and-Floating-Elements pull request #7
Opened 2021-02-18 00:47 UTC by pountzas

# Added files
- index.html 
- styles.css
- /images/

2021-02-18 17:46 UTC, GzimAsani requested changes
# Status: Changes Required :recycle:
Hello **Team** 👋 Good job implementing so far :muscle:, however there are some more changes that you have to implement

Required changes:
- [ ] Add social media icons which are between title and the main picture 
- [ ] Add the comments button and social media icons at the bottom of the page, this should be after  the line div in line 205
- [ ] Add the `More in Space and Astronomy` and `Most Popular` sections 
- [ ] You are using repated css code like _display: flex_ 4 times and float 5 times this is bad CSS practice what you can do is create a class like `.grid { display: grid; }` and use it every time you need
- [ ] Kindly check the comments below

# You got this :muscle: 

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

2021-02-18 17:46 UTC, GzimAsani commented on index.html
> +                <button class="button" type="button">LOG IN</button>
Please change the color of these buttons and make them look as the original

2021-02-18 17:46 UTC, GzimAsani commented on index.html
> +                    <span>Alan Guth was one of the first physicists to hypothesize the existence of inflation, which explains how the universe expanded so uniformly and so quickly in the instant afte
This line is extending more than the picture, kindly fix it

2021-02-18 17:46 UTC, GzimAsani commented on index.html
> +                <h4>Editors’ Picks</h4>
This section is extending more than it should in to the right side which is making your site to expand more than it should, kindly fix this.

2021-02-19 04:20 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi Team
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested # changes 👇. 
- [ ] Add a more detailed description in your pull request.
- [ ] Add the More in Space and Astronomy and Most Popular sections
- [ ] Remove inline Styling
- [ ] Please add MIT license in the README file

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-02-19 04:20 UTC, umairarshadbutt commented on index.html
> +                <img src="./images/magnifier.png" style="width:20px" alt="search">
Remove inline Styling

2021-02-19 17:18 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @pountzas :wave:

__You've done excellently well so far. Your project is looking ready for approval :wink: 
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You've highlighted how to clone the project in the Setup section of the Readme, please complete this section by pointing out how to run the project on the browser to your users. It is always better to have a complete Readme without any assumption that the users know how to find their way.
- [ ] The `Issues page` and the `MIT license` links provided on the readme are broken. Please ensure that the MIT license file is present and the links are working.
- [ ] Kindly check the image below. I believe the date is in the wrong place.
![date](https://user-images.githubusercontent.com/26856491/108537133-89ca2f80-72dd-11eb-8caa-7714e4072a93.png)

- [ ] Your `Most Popular` section is a bit different from the one on the original page. Please check the table below and make necessary adjustments: take note of the spacings and alignments.

| Your Page | Original Page |
| -------------- | ------------------ |
| ![clone](https://user-images.githubusercontent.com/26856491/108537685-33112580-72de-11eb-8481-79d8fb45215a.png) | ![original](https://user-images.githubusercontent.com/26856491/108537708-399f9d00-72de-11eb-8743-152600265158.png) |

**[ OPTIONAL CHANGES ]**

- [ ] For subsequent commits, try to be more professional with your commit messages. I believe using messages like `code review fix 7th try test1` is not the best. Check out [this article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) on how to write better commit messages.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-02-19 20:02 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-19 20:26 UTC, merged